name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubicloud-standard-8
    environment: production
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the postgres-extensions repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tag
        id: tagger
        run: echo "::set-output name=tag::$(git describe --tags HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/porter-dev/postgres-extensions:${{ steps.tagger.outputs.tag }}
            ghcr.io/porter-dev/postgres-extensions:latest